### ISSUE TITLE
Recognition failed in the app on Windows due to unsupported prototxt

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-crowdsource-dnn-optimization#23]
caffe-classification on Window is built and run successfully, I can see predictions for default image in the console.

dnn-proxy-caffe-cpu is built too, found and loaded by the app:
![image](https://cloud.githubusercontent.com/assets/22535028/22916524/93ba5b60-f2b1-11e6-8872-a77c394759f6.png)

but after running it fails (and therefore the app is crashed) with message:

```
F0213 18:31:22.879647  2720 layer_factory.cpp:62] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Input (known types: Convolution, Eltwise, LRN, Pooling, Power, ReLU, Sigmoid, Softmax, Split, TanH)
```

this error message is contained in logs in directory _bin\logs_

It seems, the message tells about section in the prototxt file
```
input: "data"
input_shape: {
  dim: 1
  dim: 3
  dim: 227
  dim: 227
}
```
prototxt file, prepared by the app, is in _bin/tmp_ directory

**Comment by psyhtest** [comment]
@Chunosov It seems that support for the old prototxt format has been finally removed from Caffe. I previously had to convert a few models from the new format into the old format in order to benchmark a stale experimental branch e.g. for AlexNet:
```
layer {
 -  name: "data"
 -  type: "Input"
 -  top: "data"
 -  input_param { shape: { dim: $#batch_size#$ dim: 3 dim: 227 dim: 227 } }
 +input: "data"
 +input_shape: {
 +  dim: $#batch_size#$
 +  dim: 3
 +  dim: 227
 +  dim: 227
  }
```

Please see [this commit](https://github.com/dividiti/ck-caffe/commit/6823c381d8095838837a8d7817e20f9816fdbd70#diff-0f9ff49d04d5dae67d1768e48b18c97e) for details.

Do you mind converting all the models into the new format?

**Comment by Chunosov** [comment]
I'm confused why caffe-classificaton runs smoothly with the same old format of prototxt...
_CK/ck-caffe/program/caffe-classification/tmp/*.prototxt_ contains input_shape section too...

**Comment by dsavenko** [comment]
Fixed in PR https://github.com/dividiti/crowdsource-video-experiments-on-desktop/pull/24
