### ISSUE TITLE
Unable to reload proxy

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-crowdsource-dnn-optimization#6]
1) Selected CPU proxy
2) Start execution
3) Stop execution
4) Select OpenCL type of proxy
5) Start execution
6) App crashed because unable to load another version of caffe lib while other dependencies loaded successfully:

LOG:
Loading dependencies. Count: 10
Load dep lib 10 "/opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-sdk/lib64/libOpenCL.so"
Load dep lib 9 "/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so"
Load dep lib 8 "/home/nikolay/CK-TOOLS/lib-clblast-development-gcc-5.4.0-linux-64/install/lib/libclblast.so"
Load dep lib 7 "/usr/lib/x86_64-linux-gnu/libopencv_core.so"
Load dep lib 6 "/home/nikolay/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-trunk-gcc-5.4.0-linux-64/install/lib/libcaffe.so"
Segmentation fault (core dumped)

See loading lib code in recognizer.cpp
QString Recognizer::loadDeps(const QStringList &depLibs)

**Comment by dsavenko** [comment]
This is actually hard to fix. What we're doing here is loading two variants of the same library built with different options. When the first variant is unloaded, some remnants remain (in our case, static initializers of some function variables), and they affect the second variant when it's trying to load. That's why it fails to load.

I'm not sure why this happens. But, generally speaking, loading and unloading DLLs is not a safe pattern. I mean there is no general solution to make it work all the time. Some DLLs may corrupt memory of the others, or leave remnants in arbitrary places in memory, which will prevent others (or themselves) to load afterwards. 

So, our proposal is to change the model the desktop app is functioning — to make it a thinner client. We propose to introduce a CK command to do what the desktop app does, but in command line. Say, if a user runs `ck run program:video-experiments --engine=<engine UOA> --model=<model UOA> --source=<dataset UOA>`, it starts the recognition process and repeatedly prints the following information to terminal (for each image it recognizes):
```
Image path
Recognition results
FPS
```
This way, the user may run video experiments on any machine even without X server. 

**Let me reiterate, I'm not speaking about running the desktop app from the terminal via `ck run` here. I'm speaking of a separate console application (no GUI).**

And the desktop app would merely spawn a new process of that console application and parse its output. 

Please, share your thoughts. @psyhtest @gfursin @DVEfremov

**Comment by dsavenko** [comment]
There is also a similar problem on Windows regarding loading Caffe DLLs at runtime. If we agree to move to the described execution model, that problem will also go away.

**Comment by gfursin** [comment]
As we discussed today - looks reasonable, but please keep compatibility with Android version of classification!

**Comment by dsavenko** [comment]
Fixed in PR https://github.com/dividiti/crowdsource-video-experiments-on-desktop/pull/24
